/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILETRANS_H_RPCGEN
#define _FILETRANS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define BLOCK 1024

typedef char filechunk[BLOCK];

typedef char *filename;

struct buffer {
	filename name;
	filechunk data;
	int numbytes;
};
typedef struct buffer buffer;

#define FILETRANSFER_PROG 0x31230000
#define FILETRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILETRANSFER_PROC 1
extern  int * filetransfer_proc_1(buffer *, CLIENT *);
extern  int * filetransfer_proc_1_svc(buffer *, struct svc_req *);
extern int filetransfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILETRANSFER_PROC 1
extern  int * filetransfer_proc_1();
extern  int * filetransfer_proc_1_svc();
extern int filetransfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filechunk (XDR *, filechunk);
extern  bool_t xdr_filename (XDR *, filename*);
extern  bool_t xdr_buffer (XDR *, buffer*);

#else /* K&R C */
extern bool_t xdr_filechunk ();
extern bool_t xdr_filename ();
extern bool_t xdr_buffer ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILETRANS_H_RPCGEN */
