/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "filetrans.h"

bool_t
xdr_filechunk (XDR *xdrs, filechunk objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, BLOCK,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_filename (XDR *xdrs, filename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, BLOCK))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buffer (XDR *xdrs, buffer *objp)
{
	register int32_t *buf;

	 if (!xdr_filename (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_filechunk (xdrs, objp->data))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numbytes))
		 return FALSE;
	return TRUE;
}
